---

# Install Haproxy for CentOS

# for now fail if it's not a Red Hat based system
- name: Check OS ( GPDB )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat'

- name: Installation of Haproxy for CentOS
  include: haproxy-install.yml
  tags: install

- name: Uninstallation of Haproxy for CentOS
  include: haproxy-uninstall.yml
  tags: uninstall

- name: Upgrade of Haproxy for CentOS
  include: haproxy-upgrade.yml
  tags: upgrade
